[tool.black]
line-length = 99
target-version = ["py36", "py37", "py38", "py39", "py310", "py311", "py312", "py313"]
include = '''
    \.pyi?$
'''
force-exclude = '''
/(
    \.git
  | etc
  | share
  | var
  | lib/ramble/external
  | lib/ramble/spack
  | lib/ramble/llnl
  | __pycache__
)/
'''
