# Copyright 2022-2024 The Ramble Authors
# 
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

ramble:
  variables:
    processes_per_node: 1
    mpi_command: ''
    batch_submit: '{execute_experiment}'
  applications:
    hostname: # Application name, from `ramble list`
      workloads:
        local: # Workload name from application, in `ramble info <app>`
          experiments:
            test: # Arbitrary experiment name
              variables:
                n_ranks: 1
  software:
    packages: {}
    environments: {}
