# -------------------------------------------------------------------------
# This is the default ramble configuration file.
#
# Settings here are versioned with Ramble and are intended to provide
# sensible defaults out of the box. Ramble maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-ramble-instance settings (overrides defaults):
#   $RAMBLE_ROOT/etc/ramble/config.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.ramble/config.yaml
# -------------------------------------------------------------------------
config:
  test_stage: ~/.ramble/test
  locks: true
  verify_ssl: true
  connect_timeout: 10
  checksum: true
  shell: bash
  input_cache: $ramble/var/ramble/cache
  workspace_dirs: $ramble/var/ramble/workspaces
  report_dirs: ~/.ramble/reports
  include_phase_dependencies: false
  spack:
    install:
      flags: --reuse
    concretize:
      flags: --reuse
    buildcache:
      flags: ''
    env_create:
      flags: ''
